import Head from 'next/head'
import classes from '../styles/pages/Home.module.scss'
import { User, MapPin, Calendar, Send } from 'react-feather';
import Layout from '../components/Layout/Layout';
import TimeLine from '../components/DecorElements/TimeLine/TimeLine';
import ListWithIcons from '../components/DecorElements/ListWithIcons/ListWithIcons';
import ContactBlock from '../components/DecorElements/ContactBlock/ContactBlock';
import ThreePartList from '../components/DecorElements/ThreePartList/ThreePartList';

export default function AboutMe() {
  const timelineData = [
    {
      years: '1224 - 1226',
      companyName: 'LoremIpsum',
      roleTitle: 'loremipsumsit amet',
      jobLocation: 'Ipsumville',
      jobDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic minima corrupti maxime in adipisci excepturi unde! Dignissimos accusamus minima eaque maxime sequi reiciendis, eos error."
    }
  ];

  const personalInfos = [
    {
      icon: <User />,
      text: 'Lorem Ipsum'
    },
    {
      icon: <MapPin />,
      text: 'Ipsumville'
    },
    {
      icon: <Calendar />,
      text: '1222. 01. 01'
    },
    {
      icon: <Send />,
      text: 'lorem@ipsum.do',
      href: 'mailto:lorem@ipsum.do'
    }
  ];

  const contactBlockContent = (
    <>
    <h2 className="text-gray-300 font-bold relative">
      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Mollitia asperiores incidunt voluptate numquam, <a href="#" className="contact-link clipped-text text-gradient-pink-to-purple">lorem, ipsum</a>.
    </h2>
    <span className="contact-emoji">👋</span>
    </>
  );

  const list = {
    firstList: [
      {
        text: 'Lorem'
      },
      {
        text: 'Ipsum'
      },
      {
        text: 'Dolor'
      },
      {
        text: 'Sit'
      },
    ],
    secondList: [
      {
        text: 'Lorem'
      },
      {
        text: 'Ipsum'
      },
      {
        text: 'Dolor'
      },
      {
        text: 'Sit'
      },
      {
        text: 'Amet'
      },
      {
        text: 'Lorem'
      },
      {
        text: 'Ipsum'
      },
      {
        text: 'Dolor'
      },
      {
        text: 'Lorem'
      },
      {
        text: 'Ipsum'
      },
      {
        text: 'Dolor'
      },
    ],
    thirdList: [
      {
        text: 'Lorem'
      },
      {
        text: 'Ipsum'
      },
      {
        text: 'Dolor'
      },
      {
        text: 'Sit'
      },
      {
        text: 'Amet'
      }
    ]
  };

  const content = (
    <>

      <h1 className="inline-block relative clipped-text bg-image__pink-to-purple">Lorem Ipsum.</h1>
      <h3 className="hero-heading text-white">
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nulla pariatur asperiores labore quibusdam.
      </h3>

      <ListWithIcons listItems={personalInfos} />

      <div style={{ maxWidth: "780px" }}>

      <p className="text-gray-200" style={{ marginBottom: '35px', textIndent: "5px" }}>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi dolores harum saepe, iure asperiores blanditiis possimus, fugit suscipit sequi, omnis voluptas!
      </p>
      <p className="text-gray-200" style={{ marginBottom: '35px', textIndent: '5px' }}>
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet, fugit.
        <span className="text-gray-300 font-italic">- Lorem ipsum dolor sit amet consectetur. -</span>, 
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Saepe accusamus itaque ea, sit incidunt doloremque omnis eos repudiandae totam alias id deserunt 
        quo sed ipsa molestias eius quisquam expedita eum.
      </p>

      <h3 className="inline-block relative lowercase clipped-text text-gradient-pink-to-purple test-h1 section-heading">Kompetenciák</h3>
      <ThreePartList list={list} />


      <h3 className="inline-block relative lowercase clipped-text text-gradient-pink-to-purple test-h1 section-heading">Tapasztalatok</h3>
      <TimeLine timelineData={timelineData} />

      <ContactBlock>
        {contactBlockContent}
      </ContactBlock>
      
    </div>

    </>
  );

  return (
    <>
      <Head>
        <title>Daniel Havelda | Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout 
        containerClass={classes['about-me__main']}
        mainContent={content}
      />
    </>
  );
}