import Head from 'next/head'
import Footer from '../components/Layout/Footer';
import classes from '../styles/pages/Home.module.scss'
import Header from '../components/Layout/Header';
import Navigation from '../components/Navigation/Navigation';
import DecorLines from '../components/DecorLines/DecorLines';
import { Sun } from 'react-feather';
import Layout from '../components/Layout/Layout';

export default function Home() {

  const homeContent = (
    <>
      <h1 className="inline-block relative lowercase clipped-text bg-image__pink-to-purple">Hello World.</h1>
        <h3 className="hero-heading text-gray-300">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum ullam nisi esse iusto <a href="/about-me" className="clipped-text text-primary-gradient font-bold">harum</a> veniam <a href="#" className="clipped-text text-primary-gradient font-bold">recusandae</a> sunt inventore repellat rerum.
        </h3>
    </>
  );

  return (
    <>
      <Head>
        <title>Daniel Havelda | Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout 
        containerClass={classes['homepage__main']}
        mainContent={homeContent}
      />
    </>
  );
}