import Head from 'next/head'
import Footer from '../components/Layout/Footer';
import classes from '../styles/pages/Home.module.scss'
import Header from '../components/Layout/Header';
import Navigation from '../components/Navigation/Navigation';
import DecorLines from '../components/DecorLines/DecorLines';
import { Sun } from 'react-feather';

export default function Home() {
  return (
    <>
      <Head>
        <title>Daniel Havelda | Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <DecorLines />

      <div className={['flex-container', classes['homepage__main']].join(' ')}>
        <Header>
            <Sun 
              color="#5A5A5A"
              onClick={() => console.log('NYAO')}
              className='light-mode-icon'
            />
          <Navigation />
        </Header>

        <main className="container">
          <h1 className="inline-block relative lowercase clipped-text bg-image__pink-to-purple">Hello World.</h1>
          <h3 className="hero-heading text-gray-200">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quaerat modi necessitatibus fugiat consectetur debitis eius.</h3>
          <h5 className="text-gray-500">
            <span style={{ textDecoration: 'line-through' }}>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit.
            </span>
          </h5>
        </main>

        <Footer />
      </div>
    </>
  );
}